#spring.cache.type=simple
spring.redis.host=localhost
spring.redis.port=6379

server.port=9092
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:./data/backupDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2

server.servlet.context-path=/license-server

client.id=unison-prime-client-id

# SSL Configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:certificate.jks
server.ssl.key-store-password=unison@123
server.ssl.trust-store-type=JKS

#logging.level.org.apache.coyote.http11.Http11Processor=DEBUG





