package com.avanza.license.Enum;


public enum ErrorCode {
    INVALID_USER_ID,
    INVALID_APP_ID,
    INVALID_USER_ID_APP_ID,
    MODULE_ALREADY_EXISTS,
    INVALID_SUBSCRIPTION_ID,
    INVALID_USER_SUBSCRIPTION_ID,
    INVALID_USER_ID_APP_ID_LICENSE_KEY,
    ALREADY_EXIST_USER_ID_APP_ID,
    LICENSE_KEY_EXPIRED,
    INVALID_SESSION_ID,
    MAX_USER_REACHED,
    DUPLICATE_EMAIL,
    INVALID_SESSION_ID_APP_ID,

    INVALID_CREDENTIALS,
    INVALID_PASSWORD,
    INVALID_SUBSCRIPTION_PLAN,
    INVALID_LICENSE_KEY,

    LICENSE_GENERATION_FAILED,
    APPLICATION_SAVE_FAILED,
    INVALID_MODULE_ID,
    DUPLICATE_USERNAME

}
